checks:
    php: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=src/*'
                coverage:
                    file: 'src/*'
                    format: 'clover'